# Generated by Django 4.1.2 on 2022-12-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='embedContet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('imageurl', models.ImageField(upload_to='')),
                ('published', models.BooleanField()),
                ('sulg', models.CharField(max_length=200)),
            ],
        ),
    ]
