# Generated by Django 4.1.3 on 2022-12-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todo_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
